// Maps the legacy Font Awesome 4 (`fa-*`) and Themify/Tabler (`ti-*`) class
// names used across the console to Lucide icons. <Icon> reads this, so pages
// can keep passing the old class strings (including ones stored in data).
import {
  AlarmClock,
  Archive,
  ArrowDown,
  ArrowDownUp,
  ArrowDownWideNarrow,
  ArrowLeft,
  ArrowLeftRight,
  ArrowRight,
  ArrowUp,
  ArrowUpDown,
  ArrowUpNarrowWide,
  AudioWaveform,
  Ban,
  Banknote,
  Bell,
  Book,
  BookOpen,
  BookUser,
  Bookmark,
  BookmarkCheck,
  Boxes,
  Briefcase,
  Brush,
  Building,
  Building2,
  Calendar,
  CalendarClock,
  CalendarPlus,
  CalendarRange,
  CalendarX,
  Camera,
  ChartBar,
  ChartColumn,
  ChartLine,
  ChartPie,
  Check,
  CheckCheck,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  ChevronsLeft,
  ChevronsRight,
  Circle,
  CircleAlert,
  CircleCheck,
  CircleHelp,
  CirclePlay,
  CircleUser,
  Clapperboard,
  Clipboard,
  ClipboardList,
  Clock,
  Cloud,
  CloudUpload,
  Coffee,
  Coins,
  Columns2,
  Copy,
  CreditCard,
  Crown,
  Database,
  Download,
  Droplets,
  EllipsisVertical,
  ExternalLink,
  Eye,
  EyeOff,
  File,
  FileSpreadsheet,
  FileText,
  Files,
  Film,
  Flag,
  Flame,
  Folder,
  FolderOpen,
  Forward,
  Funnel,
  GalleryHorizontal,
  Gamepad2,
  Globe,
  GraduationCap,
  GripVertical,
  Hand,
  Hash,
  Headphones,
  Heart,
  History,
  Hourglass,
  House,
  IdCard,
  Image,
  Images,
  Import,
  Info,
  Key,
  Layers,
  Layers2,
  LayoutGrid,
  LayoutList,
  LayoutTemplate,
  LifeBuoy,
  Link,
  List,
  ListChecks,
  ListTodo,
  LoaderCircle,
  Lock,
  LockKeyhole,
  LockOpen,
  LogOut,
  Mail,
  Map,
  MapPin,
  Medal,
  Megaphone,
  Menu,
  MessageCircle,
  MessageSquare,
  MessageSquareHeart,
  MessagesSquare,
  Mic,
  Minus,
  Monitor,
  Music,
  Navigation,
  NotebookPen,
  NotebookTabs,
  Package,
  PaintBucket,
  Pause,
  PenLine,
  PenTool,
  Pencil,
  Phone,
  Pin,
  Play,
  Plus,
  Pointer,
  Power,
  Presentation,
  Printer,
  Quote,
  Radio,
  Receipt,
  Redo2,
  RefreshCw,
  Repeat,
  Rocket,
  RotateCw,
  Save,
  School,
  Search,
  Send,
  Server,
  Settings,
  Share,
  Share2,
  Shield,
  ShieldCheck,
  ShoppingCart,
  Shrink,
  Signal,
  Signpost,
  SkipBack,
  Smartphone,
  Smile,
  Sparkles,
  Square,
  SquareCheck,
  SquarePen,
  SquarePlay,
  Stamp,
  Star,
  StarHalf,
  Tag,
  Target,
  TextAlignCenter,
  TextAlignEnd,
  TextAlignJustify,
  TextAlignStart,
  Ticket,
  Timer,
  ToggleRight,
  Trash2,
  TrendingDown,
  TrendingUp,
  TriangleAlert,
  Trophy,
  Tv,
  Type,
  Underline,
  Undo2,
  Upload,
  User,
  UserCheck,
  UserPlus,
  UserSearch,
  Users,
  Video,
  VideoOff,
  Volume2,
  Wallet,
  WandSparkles,
  X,
  Zap,
  ZoomIn,
} from 'lucide-react';

// `fill: true` marks icons that were solid glyphs in the old fonts.
export const ICON_MAP = {
  'fa-angle-double-left': { icon: ChevronsLeft },
  'fa-arrow-down': { icon: ArrowDown },
  'fa-arrow-right': { icon: ArrowRight },
  'fa-arrow-up': { icon: ArrowUp },
  'fa-bar-chart': { icon: ChartColumn },
  'fa-black-tie': { icon: Briefcase },
  'fa-book': { icon: Book },
  'fa-bullhorn': { icon: Megaphone },
  'fa-calendar': { icon: Calendar },
  'fa-check': { icon: Check },
  'fa-check-square-o': { icon: SquareCheck },
  'fa-circle': { icon: Circle, fill: true },
  'fa-cog': { icon: Settings },
  'fa-comments-o': { icon: MessagesSquare },
  'fa-credit-card': { icon: CreditCard },
  'fa-cubes': { icon: Boxes },
  'fa-database': { icon: Database },
  'fa-download': { icon: Download },
  'fa-exclamation-triangle': { icon: TriangleAlert },
  'fa-file-o': { icon: File },
  'fa-file-pdf-o': { icon: FileText },
  'fa-file-text-o': { icon: FileText },
  'fa-film': { icon: Film },
  'fa-fire': { icon: Flame },
  'fa-flag-checkered': { icon: Flag },
  'fa-folder-o': { icon: Folder },
  'fa-folder-open-o': { icon: FolderOpen },
  'fa-graduation-cap': { icon: GraduationCap },
  'fa-history': { icon: History },
  'fa-home': { icon: House },
  'fa-id-badge': { icon: IdCard },
  'fa-id-card-o': { icon: IdCard },
  'fa-layout-grid2': { icon: LayoutGrid },
  'fa-life-ring': { icon: LifeBuoy },
  'fa-line-chart': { icon: ChartLine },
  'fa-list-alt': { icon: List },
  'fa-list-ul': { icon: List },
  'fa-lock': { icon: Lock },
  'fa-male': { icon: User },
  'fa-map-marker': { icon: MapPin },
  'fa-microphone': { icon: Mic },
  'fa-minus': { icon: Minus },
  'fa-mobile': { icon: Smartphone },
  'fa-money': { icon: Banknote },
  'fa-paper-plane': { icon: Send },
  'fa-pencil': { icon: Pencil },
  'fa-pencil-square-o': { icon: SquarePen },
  'fa-phone': { icon: Phone },
  'fa-play-circle-o': { icon: CirclePlay },
  'fa-plus': { icon: Plus },
  'fa-question-circle': { icon: CircleHelp },
  'fa-search': { icon: Search },
  'fa-search-plus': { icon: ZoomIn },
  'fa-shield': { icon: Shield },
  'fa-shopping-cart': { icon: ShoppingCart },
  'fa-sign-out': { icon: LogOut },
  'fa-smile-o': { icon: Smile },
  'fa-spinner': { icon: LoaderCircle },
  'fa-square-o': { icon: Square },
  'fa-star': { icon: Star, fill: true },
  'fa-star-half-o': { icon: StarHalf },
  'fa-star-o': { icon: Star },
  'fa-tasks': { icon: ListTodo },
  'fa-th-large': { icon: LayoutGrid },
  'fa-thumb-tack': { icon: Pin },
  'fa-times': { icon: X },
  'fa-trophy': { icon: Trophy },
  'fa-tv': { icon: Tv },
  'fa-user': { icon: User },
  'fa-user-circle': { icon: CircleUser },
  'fa-user-circle-o': { icon: CircleUser },
  'fa-user-plus': { icon: UserPlus },
  'fa-users': { icon: Users },
  'fa-video-camera': { icon: Video },
  'fa-whatsapp': { icon: MessageCircle },
  'fa-wpforms': { icon: ClipboardList },
  'ti-address-book': { icon: BookUser },
  'ti-agenda': { icon: NotebookTabs },
  'ti-alarm-clock': { icon: AlarmClock },
  'ti-alert': { icon: TriangleAlert },
  'ti-alert-circle': { icon: CircleAlert },
  'ti-alert-triangle': { icon: TriangleAlert },
  'ti-align-center': { icon: TextAlignCenter },
  'ti-align-justify': { icon: TextAlignJustify },
  'ti-align-left': { icon: TextAlignStart },
  'ti-align-right': { icon: TextAlignEnd },
  'ti-angle-double-left': { icon: ChevronsLeft },
  'ti-angle-double-right': { icon: ChevronsRight },
  'ti-angle-down': { icon: ChevronDown },
  'ti-angle-left': { icon: ChevronLeft },
  'ti-angle-right': { icon: ChevronRight },
  'ti-angle-up': { icon: ChevronUp },
  'ti-announcement': { icon: Megaphone },
  'ti-archive': { icon: Archive },
  'ti-arrow-down': { icon: ArrowDown },
  'ti-arrow-left': { icon: ArrowLeft },
  'ti-arrow-right': { icon: ArrowRight },
  'ti-arrow-up': { icon: ArrowUp },
  'ti-arrows-horizontal': { icon: ArrowLeftRight },
  'ti-arrows-right-left': { icon: ArrowLeftRight },
  'ti-arrows-shrink-1': { icon: Shrink },
  'ti-arrows-vertical': { icon: ArrowUpDown },
  'ti-back-left': { icon: Undo2 },
  'ti-back-right': { icon: Redo2 },
  'ti-ban': { icon: Ban },
  'ti-bar-chart': { icon: ChartColumn },
  'ti-bar-chart-alt': { icon: ChartBar },
  'ti-bell': { icon: Bell },
  'ti-blackboard': { icon: Presentation },
  'ti-blur': { icon: Droplets },
  'ti-bolt': { icon: Zap },
  'ti-book': { icon: Book },
  'ti-book-open': { icon: BookOpen },
  'ti-bookmark': { icon: Bookmark },
  'ti-bookmark-alt': { icon: BookmarkCheck },
  'ti-brand-whatsapp': { icon: MessageCircle },
  'ti-brand-youtube': { icon: SquarePlay },
  'ti-briefcase': { icon: Briefcase },
  'ti-brush': { icon: Brush },
  'ti-building': { icon: Building2 },
  'ti-building-community': { icon: Building },
  'ti-calendar': { icon: Calendar },
  'ti-calendar-plus': { icon: CalendarPlus },
  'ti-calendar-stats': { icon: CalendarRange },
  'ti-calendar-time': { icon: CalendarClock },
  'ti-calendar-x': { icon: CalendarX },
  'ti-camera': { icon: Camera },
  'ti-check': { icon: Check },
  'ti-check-box': { icon: SquareCheck },
  'ti-checks': { icon: CheckCheck },
  'ti-chevron-down': { icon: ChevronDown },
  'ti-chevron-up': { icon: ChevronUp },
  'ti-circle-check': { icon: CircleCheck },
  'ti-circle-filled': { icon: Circle, fill: true },
  'ti-clipboard': { icon: Clipboard },
  'ti-clock': { icon: Clock },
  'ti-close': { icon: X },
  'ti-cloud': { icon: Cloud },
  'ti-cloud-up': { icon: CloudUpload },
  'ti-cloud-upload': { icon: CloudUpload },
  'ti-coin': { icon: Coins },
  'ti-comment': { icon: MessageSquare },
  'ti-comment-alt': { icon: MessageSquare },
  'ti-comments': { icon: MessagesSquare },
  'ti-comments-smiley': { icon: MessageSquareHeart },
  'ti-control-pause': { icon: Pause },
  'ti-control-play': { icon: Play },
  'ti-control-skip-backward': { icon: SkipBack },
  'ti-control-stop': { icon: Square },
  'ti-copy': { icon: Copy },
  'ti-credit-card': { icon: CreditCard },
  'ti-crown': { icon: Crown },
  'ti-cup': { icon: Coffee },
  'ti-desktop': { icon: Monitor },
  'ti-device-desktop': { icon: Monitor },
  'ti-direction': { icon: Signpost },
  'ti-direction-alt': { icon: Signpost },
  'ti-download': { icon: Download },
  'ti-email': { icon: Mail },
  'ti-envelope': { icon: Mail },
  'ti-exchange-vertical': { icon: ArrowDownUp },
  'ti-export': { icon: Share },
  'ti-external-link': { icon: ExternalLink },
  'ti-eye': { icon: Eye },
  'ti-eye-off': { icon: EyeOff },
  'ti-face-smile': { icon: Smile },
  'ti-file': { icon: File },
  'ti-file-pdf': { icon: FileText },
  'ti-file-spreadsheet': { icon: FileSpreadsheet },
  'ti-file-text': { icon: FileText },
  'ti-files': { icon: Files },
  'ti-filter': { icon: Funnel },
  'ti-folder': { icon: Folder },
  'ti-folder-open': { icon: FolderOpen },
  'ti-forward': { icon: Forward },
  'ti-gallery': { icon: Images },
  'ti-game': { icon: Gamepad2 },
  'ti-hand-drag': { icon: GripVertical },
  'ti-hand-point-up': { icon: Pointer },
  'ti-hand-stop': { icon: Hand },
  'ti-hash': { icon: Hash },
  'ti-headphone': { icon: Headphones },
  'ti-headphone-alt': { icon: Headphones },
  'ti-headphones': { icon: Headphones },
  'ti-heart': { icon: Heart },
  'ti-help': { icon: CircleHelp },
  'ti-help-alt': { icon: CircleHelp },
  'ti-history': { icon: History },
  'ti-home': { icon: House },
  'ti-hourglass': { icon: Hourglass },
  'ti-id-badge': { icon: IdCard },
  'ti-image': { icon: Image },
  'ti-import': { icon: Import },
  'ti-info': { icon: Info },
  'ti-info-alt': { icon: Info },
  'ti-info-circle': { icon: Info },
  'ti-key': { icon: Key },
  'ti-layers': { icon: Layers },
  'ti-layers-alt': { icon: Layers2 },
  'ti-layout': { icon: LayoutTemplate },
  'ti-layout-column2': { icon: Columns2 },
  'ti-layout-grid2': { icon: LayoutGrid },
  'ti-layout-list': { icon: LayoutList },
  'ti-layout-list-thumb': { icon: LayoutList },
  'ti-layout-media-overlay': { icon: Image },
  'ti-layout-slider': { icon: GalleryHorizontal },
  'ti-link': { icon: Link },
  'ti-list': { icon: List },
  'ti-list-check': { icon: ListChecks },
  'ti-loader': { icon: LoaderCircle },
  'ti-location-arrow': { icon: Navigation },
  'ti-location-pin': { icon: MapPin },
  'ti-lock': { icon: Lock },
  'ti-mail': { icon: Mail },
  'ti-map-2': { icon: Map },
  'ti-map-pin': { icon: MapPin },
  'ti-medal': { icon: Medal },
  'ti-medall': { icon: Medal },
  'ti-menu-alt': { icon: Menu },
  'ti-microphone': { icon: Mic },
  'ti-minus': { icon: Minus },
  'ti-mobile': { icon: Smartphone },
  'ti-money': { icon: Banknote },
  'ti-more-alt': { icon: EllipsisVertical },
  'ti-mortar-board': { icon: GraduationCap },
  'ti-movie': { icon: Film },
  'ti-music': { icon: Music },
  'ti-na': { icon: Ban },
  'ti-new-window': { icon: ExternalLink },
  'ti-notepad': { icon: NotebookPen },
  'ti-package': { icon: Package },
  'ti-paint-bucket': { icon: PaintBucket },
  'ti-pencil': { icon: Pencil },
  'ti-pencil-alt': { icon: SquarePen },
  'ti-photo': { icon: Image },
  'ti-pie-chart': { icon: ChartPie },
  'ti-pin': { icon: Pin },
  'ti-pin2': { icon: Pin },
  'ti-player-play': { icon: Play },
  'ti-player-stop': { icon: Square },
  'ti-plus': { icon: Plus },
  'ti-power-off': { icon: Power },
  'ti-printer': { icon: Printer },
  'ti-quote': { icon: Quote },
  'ti-radio': { icon: Radio },
  'ti-receipt': { icon: Receipt },
  'ti-refresh': { icon: RefreshCw },
  'ti-reload': { icon: RotateCw },
  'ti-repeat': { icon: Repeat },
  'ti-rocket': { icon: Rocket },
  'ti-save': { icon: Save },
  'ti-school': { icon: School },
  'ti-search': { icon: Search },
  'ti-send': { icon: Send },
  'ti-server': { icon: Server },
  'ti-settings': { icon: Settings },
  'ti-share': { icon: Share2 },
  'ti-shield': { icon: Shield },
  'ti-shield-check': { icon: ShieldCheck },
  'ti-shield-lock': { icon: LockKeyhole },
  'ti-shopping-cart': { icon: ShoppingCart },
  'ti-signal': { icon: Signal },
  'ti-sort-ascending': { icon: ArrowUpNarrowWide },
  'ti-sort-descending': { icon: ArrowDownWideNarrow },
  'ti-sparkles': { icon: Sparkles },
  'ti-stamp': { icon: Stamp },
  'ti-star': { icon: Star },
  'ti-stats-down': { icon: TrendingDown },
  'ti-stats-up': { icon: TrendingUp },
  'ti-support': { icon: LifeBuoy },
  'ti-tag': { icon: Tag },
  'ti-target': { icon: Target },
  'ti-text': { icon: Type },
  'ti-thumb-tack': { icon: Pin },
  'ti-ticket': { icon: Ticket },
  'ti-time': { icon: Clock },
  'ti-timer': { icon: Timer },
  'ti-toggle-right': { icon: ToggleRight },
  'ti-trash': { icon: Trash2 },
  'ti-trophy': { icon: Trophy },
  'ti-underline': { icon: Underline },
  'ti-unlock': { icon: LockOpen },
  'ti-upload': { icon: Upload },
  'ti-user': { icon: User },
  'ti-user-check': { icon: UserCheck },
  'ti-user-search': { icon: UserSearch },
  'ti-users': { icon: Users },
  'ti-vector': { icon: PenTool },
  'ti-video': { icon: Video },
  'ti-video-camera': { icon: Video },
  'ti-video-camera-off': { icon: VideoOff },
  'ti-video-clapper': { icon: Clapperboard },
  'ti-view-list': { icon: List },
  'ti-volume': { icon: Volume2 },
  'ti-wallet': { icon: Wallet },
  'ti-wand': { icon: WandSparkles },
  'ti-wave-sine': { icon: AudioWaveform },
  'ti-world': { icon: Globe },
  'ti-write': { icon: PenLine },
  'ti-x': { icon: X },
  'ti-zoom-in': { icon: ZoomIn },
};
