export const NAV_GROUPS = [
  { id: 'batches',     label: 'Batches',       icon: 'ti ti-layout-grid2' },
  { id: 'academics',   label: 'Academics',     icon: 'ti ti-agenda'  },
  { id: 'people',      label: 'People',        icon: 'ti ti-user'           },
  { id: 'commerce',    label: 'Commerce',      icon: 'ti ti-shopping-cart'   },
  { id: 'marketing',   label: 'Marketing',     icon: 'ti ti-announcement'        },
  { id: 'support',     label: 'Support',       icon: 'ti ti-support'       },
  { id: 'tools',       label: 'Tools',         icon: 'ti ti-settings'          },
  { id: 'admin',       label: 'Admin',         icon: 'ti ti-shield'          },
];

const screens = [
  // ── Public ───────────────────────────────────────────────────────────
  {
    path: '/login',
    title: 'Pilot Login',
    legacyHtml: 'index.html',
    controller: 'controllers/login.js',
    protected: false,
    group: null,
    icon: 'ti ti-unlock',
    summary: 'Admin authentication and token bootstrap.',
  },
  {
    path: '/verify-token',
    title: 'Token Verification',
    legacyHtml: 'verify-token.html',
    controller: 'inline',
    protected: false,
    group: null,
    icon: 'ti ti-key',
    summary: 'Developer utility for token validation.',
  },

  // ── Batches ───────────────────────────────────────────────────────────
  {
    path: '/batch',
    title: 'Batch Management',
    legacyHtml: 'batch.html',
    controller: 'controllers/batch.js',
    protected: true,
    group: 'batches',
    icon: 'ti ti-layout-grid2',
    shortCode: 'BM',
    summary: 'Batch CRUD, course enrollments, and student assignment.',
  },
  {
    path: '/live-class-scheduler',
    title: 'Live Class Scheduler',
    legacyHtml: null,
    controller: null,
    protected: true,
    group: 'batches',
    icon: 'ti ti-video-camera',
    shortCode: 'LC',
    summary: 'Schedule, host, and moderate live interactive broadcast sessions.',
  },
  {
    path: '/schedule-list',
    title: 'Schedules',
    legacyHtml: null,
    controller: null,
    protected: true,
    group: 'batches',
    icon: 'ti ti-calendar',
    shortCode: 'SC',
    summary: 'Day-schedule listing with batch links, freeze, and quick navigation to the calendar view.',
  },
  {
    path: '/schedules',
    title: 'Schedule Calendar',
    legacyHtml: null,
    controller: null,
    protected: true,
    group: null,
    icon: 'ti ti-calendar',
    summary: 'Calendar view of a single schedule; reachable from the Schedules list.',
  },

  // ── Academics ─────────────────────────────────────────────────────────
  {
    path: '/courses-list',
    title: 'Courses',
    legacyHtml: 'courses-list.html',
    controller: 'controllers/courses-list.js',
    protected: true,
    group: 'academics',
    icon: 'ti ti-book',
    shortCode: 'CR',
    summary: 'Published course listing, filters, and deep links.',
  },
  {
    path: '/test-series-list',
    title: 'Test Series',
    legacyHtml: 'test-series-list.html',
    controller: 'controllers/test-series-list.js',
    protected: true,
    group: 'academics',
    icon: 'ti ti-write',
    shortCode: 'TS',
    summary: 'Test-series definition and exam assignments.',
  },
  {
    path: '/quiz-listing',
    title: 'Quizzes',
    legacyHtml: 'quiz-listing.html',
    controller: 'controllers/quiz-listing.js',
    protected: true,
    group: 'academics',
    icon: 'ti ti-help-alt',
    shortCode: 'QZ',
    summary: 'Quiz drafts, published quizzes, and report entry points.',
  },
  {
    path: '/question-bank',
    title: 'Question Bank',
    legacyHtml: 'question-bank.html',
    controller: 'controllers/question-bank.js',
    protected: true,
    group: 'academics',
    icon: 'ti ti-server',
    shortCode: 'QB',
    summary: 'Question review, verification, solution editing, and filters.',
  },
  {
    path: '/practice-questions',
    title: 'Practice Questions',
    legacyHtml: 'practice-questions.html',
    controller: 'controllers/practice-questions.js',
    protected: true,
    group: 'academics',
    icon: 'ti ti-pencil-alt',
    shortCode: 'PQ',
    summary: 'PDF ingestion, OCR-assisted extraction, and quiz handoff.',
  },
  {
    path: '/video-content',
    title: 'Video Library',
    legacyHtml: 'video-content.html',
    controller: 'controllers/video-content.js',
    protected: true,
    group: 'academics',
    icon: 'ti ti-video-clapper',
    shortCode: 'VL',
    summary: 'Bunny.net video upload, filtering, and collection management.',
  },
  {
    path: '/bunny-admin',
    title: 'Video Hosting',
    legacyHtml: 'bunny-admin.html',
    controller: 'controllers/bunny-admin.js',
    protected: true,
    group: 'academics',
    icon: 'ti ti-cloud-up',
    shortCode: 'VH',
    summary: 'Folder-oriented Bunny.net admin surface.',
  },
  {
    path: '/class-notes',
    title: 'Class Notes',
    legacyHtml: 'class-notes.html',
    controller: 'controllers/class-notes.js',
    protected: true,
    group: 'academics',
    icon: 'ti ti-notepad',
    shortCode: 'CN',
    summary: 'Chapter-wise PDF class notes with batch visibility for the mobile app.',
  },

  // ── People ────────────────────────────────────────────────────────────
  {
    path: '/candidate-profile',
    title: 'Students',
    legacyHtml: 'candidate-profile.html',
    controller: 'controllers/candidate-profile.js',
    protected: true,
    group: 'people',
    icon: 'ti ti-id-badge',
    shortCode: 'ST',
    summary: 'Student listing, enrollment actions, and search.',
  },
  {
    path: '/student-360',
    title: 'Student 360',
    legacyHtml: null,
    controller: null,
    protected: true,
    group: 'people',
    icon: 'ti ti-target',
    shortCode: 'S360',
    summary: 'A 360° view of a student — prep journey, performance, engagement and activity.',
  },
  {
    path: '/mentor-profiles',
    title: 'Mentors',
    legacyHtml: 'mentor-profiles.html',
    controller: 'controllers/mentor-profiles.js',
    protected: true,
    group: 'people',
    icon: 'ti ti-face-smile',
    shortCode: 'MN',
    summary: 'Mentor CRUD plus assigned-student workflows.',
  },
  {
    path: '/mentor-sessions',
    title: 'Mentor Sessions',
    legacyHtml: null,
    controller: null,
    protected: true,
    group: 'people',
    icon: 'ti ti-microphone',
    shortCode: 'MS',
    summary: 'Schedule and track mentor-led Audio Rooms (getstream.io) for student mentees.',
  },
  {
    path: '/residences',
    title: 'Residences',
    legacyHtml: null,
    controller: null,
    protected: true,
    group: 'people',
    icon: 'ti ti-home',
    shortCode: 'RS',
    summary: 'Residence management, houses, occupancy and student allotments.',
  },
  {
    path: '/instructor-portfolio',
    title: 'Instructors',
    legacyHtml: 'instructor-portfolio.html',
    controller: 'controllers/instructor-portfolio.js',
    protected: true,
    group: 'people',
    icon: 'ti ti-blackboard',
    shortCode: 'IN',
    summary: 'Instructor CRUD and profile asset management.',
  },

  // ── Commerce ──────────────────────────────────────────────────────────
  {
    path: '/orders',
    title: 'Orders',
    legacyHtml: 'orders.html',
    controller: 'controllers/orders.js',
    protected: true,
    group: 'commerce',
    icon: 'ti ti-receipt',
    shortCode: 'OR',
    summary: 'Order tracking, invoice actions, and student drill-down.',
  },
  {
    path: '/payments',
    title: 'Payments',
    legacyHtml: null,
    controller: null,
    protected: true,
    group: 'commerce',
    icon: 'ti ti-credit-card',
    shortCode: 'PY',
    summary: 'All payments across orders — initial, installments, and dues.',
  },
  {
    path: '/catalog',
    title: 'Catalog',
    legacyHtml: 'catalog.html',
    controller: 'controllers/catalog.js',
    protected: true,
    group: 'commerce',
    icon: 'ti ti-package',
    shortCode: 'CT',
    summary: 'Catalog entries, publishing, and asset upload workflow.',
  },
  {
    path: '/commerce-reports',
    title: 'Reports',
    legacyHtml: null,
    controller: null,
    protected: true,
    group: 'commerce',
    icon: 'ti ti-bar-chart',
    shortCode: 'RP',
    summary: 'Order and payment reports by period, course, method, or batch.',
  },

  // ── Marketing ─────────────────────────────────────────────────────────
  {
    path: '/leads-management',
    title: 'Leads',
    legacyHtml: 'leads-management.html',
    controller: 'controllers/leads.js',
    protected: true,
    group: 'marketing',
    icon: 'ti ti-filter',
    shortCode: 'LD',
    summary: 'Lead tracking, follow-up calendar, and outreach actions.',
  },
  {
    path: '/messenger',
    title: 'Broadcast Messages',
    legacyHtml: null,
    controller: null,
    protected: true,
    group: 'marketing',
    icon: 'ti ti-envelope',
    shortCode: 'BMG',
    summary: 'Send bulk messages to students via multi-channel broadcasts.',
  },
  {
    path: '/web-content-manager',
    title: 'Web Content Manager',
    legacyHtml: 'web-content-manager.html',
    controller: 'controllers/web-content-manager.js',
    protected: true,
    group: 'marketing',
    icon: 'ti ti-world',
    shortCode: 'WC',
    summary: 'Voucher and auto-enrollment management.',
  },

  // ── Support ───────────────────────────────────────────────────────────
  {
    path: '/support',
    title: 'Support Tickets',
    legacyHtml: null,
    controller: null,
    protected: true,
    group: 'support',
    icon: 'ti ti-ticket',
    shortCode: 'SP',
    summary: 'Consolidated view for student support tickets and potential leads chats.',
  },

  // ── Tools ─────────────────────────────────────────────────────────────
  {
    path: '/offline-attendance',
    title: 'Offline Attendance',
    legacyHtml: null,
    controller: null,
    protected: true,
    group: 'tools',
    icon: 'ti ti-check-box',
    shortCode: 'OA',
    summary: 'Biometric and offline attendance reporting across batches, residences and locations.',
  },
  {
    path: '/attendance-mapping',
    title: 'Attendance Mapping',
    legacyHtml: null,
    controller: null,
    protected: true,
    group: null,
    icon: 'ti ti-direction',
    summary: 'Map attendance device keys to users at each location with access validity windows.',
  },
  {
    path: '/attendance-capture-location',
    title: 'Default Attendance Location',
    legacyHtml: null,
    controller: null,
    protected: true,
    group: null,
    icon: 'ti ti-location-pin',
    summary: 'Map batches and people to their default attendance location across multiple swipe locations.',
  },
  {
    path: '/assets',
    title: 'Assets',
    legacyHtml: null,
    controller: null,
    protected: true,
    group: 'tools',
    icon: 'ti ti-archive',
    shortCode: 'AS',
    summary: 'Asset inventory, valuation, depreciation tracking and reports.',
  },
  {
    path: '/feedback-summary',
    title: 'Feedbacks',
    legacyHtml: null,
    controller: null,
    protected: true,
    group: 'tools',
    icon: 'ti ti-comments-smiley',
    shortCode: 'FD',
    summary: 'Consolidated feedback aggregation and viewing portal.',
  },
  {
    path: '/survey-dashboard',
    title: 'Surveys',
    legacyHtml: null,
    controller: null,
    protected: true,
    group: 'tools',
    icon: 'ti ti-pie-chart',
    shortCode: 'SR',
    summary: 'Create custom surveys and view responses across targeted student batches.',
  },
  {
    path: '/icard-generator',
    title: 'ID Card Generator',
    legacyHtml: null,
    controller: null,
    protected: true,
    group: 'tools',
    icon: 'ti ti-stamp',
    shortCode: 'IC',
    summary: 'Generate student ID cards in bulk from a template and view historical generations.',
  },
  {
    path: '/digital-signage',
    title: 'Digital Signage',
    legacyHtml: null,
    controller: null,
    protected: true,
    group: 'tools',
    icon: 'ti ti-desktop',
    shortCode: 'DS',
    summary: 'Manage TV kiosks, build content timelines, broadcast emergency alerts across branches.',
  },
  {
    path: '/mobile-app-settings',
    title: 'Mobile App Settings',
    legacyHtml: null,
    controller: null,
    protected: true,
    group: 'tools',
    icon: 'ti ti-mobile',
    shortCode: 'MA',
    summary: 'Track published mobile app versions and publish release notes for each version.',
  },
  {
    path: '/forms',
    title: 'Forms',
    legacyHtml: null,
    controller: null,
    protected: true,
    group: 'tools',
    icon: 'ti ti-clipboard',
    shortCode: 'FM',
    summary: 'Configure fixed forms, dispatch them to audiences, and review submissions.',
  },
  {
    path: '/instructor-payouts',
    title: 'Instructor Payouts',
    legacyHtml: 'instructor-payouts.html',
    controller: 'controllers/instructor-time-tracker.js',
    protected: true,
    group: 'tools',
    icon: 'ti ti-money',
    shortCode: 'IP',
    summary: 'Time tracking and payout calculations.',
  },

  // ── Hidden (no sidebar entry) ─────────────────────────────────────────
  {
    path: '/landing',
    title: 'Home',
    legacyHtml: null,
    controller: null,
    protected: true,
    group: null,
    icon: 'ti ti-home',
    summary: 'Personal landing dashboard with pinned shortcuts.',
  },
  {
    path: '/candidate-detail',
    title: 'Student Details',
    legacyHtml: 'candidate-detail.html',
    controller: 'controllers/candidate-detail.js',
    protected: true,
    group: null,
    icon: 'ti ti-user',
    summary: 'Detailed candidate profile, mentor, courses, and exam history.',
  },
  {
    path: '/course-view',
    title: 'Course View',
    legacyHtml: 'course-view.html',
    controller: 'controllers/course-view.js',
    protected: true,
    group: null,
    icon: 'ti ti-eye',
    summary: 'Course detail viewer with chapter and part navigation.',
  },
  {
    path: '/course-management',
    title: 'Course Management',
    legacyHtml: 'course-management.html',
    controller: 'controllers/course-management.js',
    protected: true,
    group: null,
    icon: 'ti ti-pencil',
    summary: 'Course authoring, syllabus management, and chapter linking.',
  },
  {
    path: '/live-class-activity-planner',
    title: 'Activity Planner',
    legacyHtml: null,
    controller: null,
    protected: true,
    group: null,
    icon: 'ti ti-game',
    summary: 'Pre-configure polls and quizzes for upcoming live classes.',
  },
  {
    path: '/quiz-creation',
    title: 'Quiz Creation',
    legacyHtml: 'quiz-creation.html',
    controller: 'controllers/quiz-creation.js',
    protected: true,
    group: null,
    icon: 'ti ti-plus',
    summary: 'Quiz assembly from practice-question bundles.',
  },
  {
    path: '/quiz-attempt-report',
    title: 'Quiz Report',
    legacyHtml: 'quiz-attempt-report.html',
    controller: 'controllers/quiz-attempt-report.js',
    protected: true,
    group: null,
    icon: 'ti ti-bar-chart',
    summary: 'Quiz attempt analytics and export tools.',
  },
  {
    path: '/exam-listing',
    title: 'Exams',
    legacyHtml: 'exam-listing.html',
    controller: 'controllers/exam-listing.js',
    protected: true,
    group: null,
    icon: 'ti ti-medall',
    summary: 'Exam list, duplication, deletion, and report entry points.',
  },
  {
    path: '/exam-creation-wizard',
    title: 'Exam Creation Wizard',
    legacyHtml: 'exam-creation-wizard.html',
    controller: 'controllers/exam-creation-wizard.js',
    protected: true,
    group: null,
    icon: 'ti ti-wand',
    summary: 'Exam editor and section/question configuration.',
  },
  {
    path: '/exam-attempt-report',
    title: 'Exam Report',
    legacyHtml: 'exam-attempt-report.html',
    controller: 'controllers/exam-attempt-report.js',
    protected: true,
    group: null,
    icon: 'ti ti-stats-up',
    summary: 'Exam attempt analytics and export tools.',
  },
];

// ─── Path → view-permission mapping (RBAC) ─────────────────────────────────
// Keys must match `src/lib/permissions.js` (PERMS) and the API enum.
// Paths absent from this map are treated as "no extra permission required"
// (still gated by authentication).
const VIEW_PERMISSIONS = {
  '/landing': null,
  // Batches
  '/batch': 'batches.view',
  '/live-class-scheduler': 'liveClass.view',
  '/live-class-activity-planner': 'liveClass.view',
  '/schedules': 'batches.view',
  '/schedule-list': 'batches.view',
  // Academics
  '/courses-list': 'courses.view',
  '/course-view': 'courseView.view',
  '/course-management': 'courseAuthoring.view',
  '/test-series-list': 'testSeries.view',
  '/quiz-listing': 'quizzes.view',
  '/quiz-creation': 'quizAuthoring.view',
  '/quiz-attempt-report': 'quizReports.view',
  '/exam-listing': 'exams.view',
  '/exam-creation-wizard': 'exams.edit',
  '/exam-attempt-report': 'exams.view',
  '/question-bank': 'questionBank.view',
  '/practice-questions': 'practiceQuestions.view',
  '/video-content': 'videos.view',
  '/bunny-admin': 'videoHosting.view',
  '/class-notes': 'classNotes.view',
  // People
  '/candidate-profile': 'students.view',
  '/candidate-detail': 'studentDetail.view',
  '/student-360': 'studentDetail.view',
  '/mentor-profiles': 'mentors.view',
  '/mentor-sessions': 'mentorSessions.view',
  '/instructor-portfolio': 'instructors.view',
  '/residences': 'residences.view',
  // Commerce
  '/orders': 'orders.view',
  '/payments': 'orders.view',
  '/commerce-reports': 'orders.view',
  '/catalog': 'catalog.view',
  // Marketing
  '/leads-management': 'leads.view',
  '/messenger': 'broadcast.view',
  '/web-content-manager': 'webContent.view',
  // Support
  '/support': 'support.view',
  // Tools
  '/feedback-summary': 'feedback.view',
  '/survey-dashboard': 'surveys.view',
  '/offline-attendance': 'attendance.view',
  '/attendance-mapping': 'attendance.mapping.view',
  '/attendance-capture-location': 'attendance.mapping.view',
  '/assets': 'assets.view',
  '/instructor-payouts': 'payouts.view',
  '/icard-generator': 'icard.view',
};

// Attach `viewPermission` to each screen using the map.
screens.forEach((screen) => {
  if (Object.prototype.hasOwnProperty.call(VIEW_PERMISSIONS, screen.path)) {
    screen.viewPermission = VIEW_PERMISSIONS[screen.path];
  }
});

export const publicScreens = screens.filter((screen) => !screen.protected);
export const protectedScreens = screens.filter((screen) => screen.protected);
export const allScreens = screens;
export const defaultProtectedRoute = '/landing';
